global:
  scrape_interval: 5s

scrape_configs:
  # OTEL Collector internal metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['localhost:8888']
    metrics_path: '/metrics'

  # OTEL Collector OTLP metrics (via Prometheus exporter)
  - job_name: 'otel-collector-otlp'
    static_configs:
      - targets: ['localhost:8889']
    metrics_path: '/metrics'

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'

  # Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    metrics_path: '/metrics'

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

  # Node Exporter for Ubuntu server
  - job_name: "node"
    static_configs:
      - targets: ['192.168.1.250:9100']

  # Prometheus metrics for Ubuntu Client
  - job_name: 'kubuntu-translator-prometheus'
    static_configs:
      - targets: ['192.168.1.9:8000']

  # Prometheus metrics for Identity service
  - job_name: 'identity-service-prometheus'
    static_configs:
      - targets: ['192.168.1.46:8001']

  - job_name: 'translator_service'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Replace 8000 with your FastAPI port
    metrics_path: '/api/v1/metrics'
